name: hexlet-ci-app

on:
  - push
  - pull_request
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
     matrix:
      node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run make setup
      run: make setup

    - name: Run make test
      run: make test

    - name: Run make lint
      run: make lint

    - name: Print Hello from Hexlet
      uses: hexlet-components/hello-from-hexlet-action@release