name: hexlet-ci-app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run make setup
      run: make setup

    - name: Run make test
      run: make test

    - name: Run make lint
      run: make lint

    - name: Print Hello from Hexlet
      uses: hexlet-components/hello-from-hexlet-action@release